name: Tests

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: npm ci

    - run: npm run firebase -- emulators:exec "npm test" --import spec/fixture/ --project hello-firebase-experiment
      env:
        CI: true

